# Generated by Django 4.1.1 on 2022-09-07 12:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(max_length=10, unique=True, verbose_name='닉네임')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='이메일')),
                ('gender', models.CharField(choices=[('남자', 'Male'), ('여자', 'Female')], max_length=4, null=True, verbose_name='성별')),
                ('password', models.CharField(max_length=256, verbose_name='비밀번호')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='전화번호')),
                ('birth_date', models.DateTimeField(null=True, verbose_name='생일')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('is_active', models.BooleanField(default=True, verbose_name='계정 활성화 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 권한')),
                ('is_artist', models.BooleanField(default=False, verbose_name='작가 계정 여부')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ArtistApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='성함')),
                ('email', models.EmailField(max_length=50, verbose_name='이메일')),
                ('gender', models.CharField(choices=[('남', 'Male'), ('여', 'Female')], max_length=4, verbose_name='성별')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='연락처')),
                ('date_of_birth', models.DateTimeField(verbose_name='생년월일')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='검토 상태')),
            ],
            options={
                'db_table': 'artist_applications',
            },
        ),
    ]
