# Generated by Django 4.1.1 on 2022-09-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertype',
            table='user_types',
        ),
    ]
